# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nbadb
      MYSQL_USER: shingo
      MYSQL_PASSWORD: shingo

    ports:
      - 3306:3306 #コンテナ外部のアクセスポート
