spring:
  datasource:
    url: "jdbc:mysql://localhost/nbadb"
    username: "shingo"
    password: "shingo"
  sql:
    init:
      mode: "always"
      encoding: "utf-8"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 自分で名前決めれる
logging.file.name: "app.log"

logging:
  level:
    root: INFO

  logback:
    rollingpolicy:
      max-file-size: 1MB



