spring:
  datasource:
    url: "jdbc:mysql://localhost/nbadb"
    username: "shingo"
    password: "shingo"
  sql:
    init:
      mode: "always"
      encoding: "utf-8"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

